[project]
name = "hw1-pytorch-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nhanncv", email = "vinhnhan1999bc@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
hw1-pytorch-tutorial = "hw1_pytorch_tutorial:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
